#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a firefox private=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom --experimental-backends -b &

~/.config/polybar/./launch.sh
bspc config focus_follows_pointer true
bspc config border_width 0
feh --bg-fill /home/flyingbiker/Pictures/wp10990842-debian-linux-wallpapers.jpg
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-1 --off &
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a qemu-system-x86 state=floating border=off follow=on
